version: '3.5'

services:
  postgres:
    container_name: local_postgres
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-default_db_local}
    volumes:
      - local_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local_postgres_net
    restart: always

  pgadmin:
    container_name: local_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-default@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1234QWERasdf}
    volumes:
       - local_pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - local_postgres_net
    restart: always

networks:
  local_postgres_net:
    driver: bridge

volumes:
    local_postgres:
    local_pgadmin:
